spring.application.name=GokartAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/GokartDB
spring.datasource.username=postgres
spring.datasource.password=12345

# Automatikus táblalétrehozás és frissítés
spring.jpa.hibernate.ddl-auto=update

# SQL lekérdezések kiírása a konzolra (ellenőrzéshez)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true